"""Explicit layer providers, availability, units and scientific legends."""
from services.presentation import LABELS
LAYERS=[{'id':'none','name':'Grayscale base only','kind':'base','provider':'Natural Earth','variable':'','unit':'','min':0,'max':1,'time':False,'available':True}, {'id':'radar','name':'Radar reflectivity · RainViewer','kind':'tiles','provider':'RainViewer','variable':'','unit':'dBZ','min':-10,'max':60,'time':True,'available':True}, {'id':'coverage','name':'Radar coverage mask','kind':'coverage','provider':'RainViewer','variable':'','unit':'Covered / no radar','min':0,'max':1,'time':False,'available':True}]
FIELDS={'temperature_2m':('°C',-20,40),'apparent_temperature':('°C',-20,40),'dew_point_2m':('°C',-20,30),'precipitation':('mm',0,10),'snowfall':('cm',0,5),'snow_depth':('m',0,1),'wind_speed_10m':('m/s',0,25),'wind_gusts_10m':('m/s',0,35),'pressure_msl':('hPa',980,1040),'cloud_cover':('%',0,100),'cloud_cover_low':('%',0,100),'cloud_cover_mid':('%',0,100),'cloud_cover_high':('%',0,100),'visibility':('m',0,25000),'cape':('J/kg',0,3000),'uv_index':('',0,12),'freezing_level_height':('m',0,5000),'soil_temperature_0cm':('°C',-10,40),'soil_moisture_0_to_1cm':('m³/m³',0,.5),'shortwave_radiation':('W/m²',0,1000),'us_aqi':('AQI',0,300),'european_aqi':('AQI',0,100),'pm2_5':('μg/m³',0,100),'pm10':('μg/m³',0,150),'ozone':('μg/m³',0,200),'nitrogen_dioxide':('μg/m³',0,100),'sulphur_dioxide':('μg/m³',0,100),'carbon_monoxide':('μg/m³',0,500),'dust':('μg/m³',0,100),'aerosol_optical_depth':('',0,1),'wave_height':('m',0,6),'wave_direction':('°',0,360),'wave_period':('s',0,20),'swell_wave_height':('m',0,6),'sea_surface_temperature':('°C',0,30),'ocean_current_velocity':('m/s',0,2),'sea_level_height_msl':('m',-2,2)}
AIR={'us_aqi','european_aqi','pm2_5','pm10','ozone','nitrogen_dioxide','sulphur_dioxide','carbon_monoxide','dust','aerosol_optical_depth'}
MARINE={'wave_height','wave_direction','wave_period','swell_wave_height','sea_surface_temperature','ocean_current_velocity','sea_level_height_msl'}
for key,(unit,lo,hi) in FIELDS.items():LAYERS.append({'id':key,'name':LABELS.get(key,key)+' · sampled model','kind':'samples','provider':'Open-Meteo / CAMS Global' if key in AIR else 'Open-Meteo Marine' if key in MARINE else 'NOAA GFS via Open-Meteo','variable':key,'unit':unit,'min':lo,'max':hi,'time':True,'available':True})
LAYERS.extend([{'id':'alerts','name':'Official alert areas · selected location','kind':'vector','provider':'ECCC / NWS','variable':'','unit':'Official source severity','min':0,'max':1,'time':False,'available':True}])
for key,name in [('lightning','Observed lightning'),('cin','Convective inhibition'),('particles','Animated wind particles'),('isobars','Pressure contours'),('global_forecast_tiles','Global forecast raster tiles')]:LAYERS.append({'id':key,'name':name+' · unavailable','kind':'unsupported','provider':'No verified provider / renderer configured','variable':'','unit':'','min':0,'max':1,'time':False,'available':False})
def layer(identity):return next((l for l in LAYERS if l['id']==identity),LAYERS[0])
def colors(palette):return ['#404040','#747474','#a6a6a6','#ddd','#fff'] if palette=='grayscale' else ['#454d9e','#5687ad','#c6cb8b','#e8b057','#b45a54']
def color(value,definition,palette):
 if value is None:return '#777777'
 position=max(0,min(.999999,(value-definition['min'])/max(1e-9,definition['max']-definition['min'])));return colors(palette)[int(position*5)]
