import math
from services.state import DEFAULT_PREFS
OPTIONS={'defaultZoom':[1,4,12,32],'defaultLayer':['radar','temperature_2m','precipitation','us_aqi','none'],'distance':['metric','imperial'],'dateFormat':['ddd dd MMM','yyyy-MM-dd','MM/dd/yyyy'],'temperature':['C','F'],'wind':['km/h','m/s','mph','knots'],'pressure':['hPa','kPa','mmHg','inHg'],'precipitation':['mm','in'],'visibility':['km','mi'],'density':['compact','comfortable','spacious'],'palette':['colorblind','grayscale'],'model':['best_match','ecmwf_ifs025','gfs_seamless','gem_seamless','icon_seamless'],'aqi':['us_aqi','european_aqi'],'horizon':[24,48,72,168],'forecastDays':[7,10,16],'refreshMinutes':[10,15,30,60],'cacheMB':[32,64,96,192],'lineWidth':[1,2,3,4],'radarSpeed':[750,1500,3000],'mapOpacity':[.3,.5,.7,1.]}
LABELS={'mapHome':'Show Home marker','defaultZoom':'Default map zoom (when view is not remembered)','defaultLayer':'Default map layer (when view is not remembered)','offline':'Offline mode (weather requests paused)','distance':'Height / marine distance','dateFormat':'Date display format','temperature':'Temperature','wind':'Wind speed','pressure':'Pressure','precipitation':'Precipitation','visibility':'Visibility distance','density':'Density','palette':'Scientific data palette','model':'Preferred weather model','aqi':'Air quality standard','horizon':'Default hourly horizon','forecastDays':'Forecast length','refreshMinutes':'Refresh interval · minutes','cacheMB':'Weather/tile cache budget · MiB','lineWidth':'Chart line width','radarSpeed':'Radar frame interval · ms','mapOpacity':'Overlay opacity','hour24':'24-hour clock','reduceMotion':'Reduce motion','highContrast':'High contrast','advanced':'Show advanced metrics','autoRefresh':'Refresh while visible','mapGrid':'Map graticule','mapDay':'Day/night terminator','mapLabels':'Map pin labels','mapPins':'Saved/Home pins','radarSmooth':'Smooth radar tiles','radarSnow':'Radar rain/snow colors','rememberMap':'Remember map view'}
def setting_rows():return [{'key':k,'label':LABELS.get(k,k),'type':'choice' if k in OPTIONS else 'toggle' if isinstance(v,bool) else 'number','options':OPTIONS.get(k,[])} for k,v in DEFAULT_PREFS.items()]
def validate(key,value):
 if key not in DEFAULT_PREFS:raise ValueError('Unknown preference')
 if key in OPTIONS:
  if value not in OPTIONS[key]:raise ValueError('Unsupported preference value')
 elif isinstance(DEFAULT_PREFS[key],bool):value=bool(value)
 elif isinstance(DEFAULT_PREFS[key],(int,float)):
  value=float(value)
  if not math.isfinite(value):raise ValueError('Preference must be finite')
  value=max(0,min(100,value))
 return value
SOURCES=[{'name':'Open-Meteo Forecast / Geocoding','data':'Modeled current, hourly, daily and city search','url':'https://open-meteo.com/en/docs','attribution':'Open-Meteo · CC BY 4.0. Geocoding based on GeoNames. Free API for personal non-commercial use.'},{'name':'Open-Meteo / Copernicus CAMS','data':'Modeled air quality and supported pollen','url':'https://open-meteo.com/en/docs/air-quality-api','attribution':'Open-Meteo and CAMS ENSEMBLE / CAMS Global atmospheric composition forecasts. CC BY 4.0; acknowledge Copernicus.'},{'name':'Open-Meteo Marine','data':'Wave, swell, ocean current and sea-level models','url':'https://open-meteo.com/en/docs/marine-weather-api','attribution':'Open-Meteo and originating model agencies. Coastal-grid accuracy limited; not for navigation.'},{'name':'Open-Meteo ERA5 / Ensembles','data':'Reanalysis history, NOAA GFS members and deterministic models','url':'https://open-meteo.com/en/docs/historical-weather-api','attribution':'Open-Meteo, ECMWF / Copernicus ERA5; NOAA GFS, ECCC GEM, ECMWF IFS, DWD ICON. CC BY 4.0.'},{'name':'Open-Meteo Previous Runs','data':'GFS current and fixed 24/48-hour lead-time archived forecasts','url':'https://open-meteo.com/en/docs/previous-runs-api','attribution':'Open-Meteo / NOAA GFS. CC BY 4.0; personal non-commercial API. Fixed lead times are not exact single-run snapshots or observed forecast errors.'},{'name':'RainViewer','data':'Radar imagery and radar coverage mask','url':'https://www.rainviewer.com/','attribution':'Weather data by RainViewer. Personal/public free API, best effort; maximum tile zoom 7. No coverage or nowcast guarantee.'},{'name':'Environment and Climate Change Canada','data':'Official Canadian alerts through MSC GeoMet OGC API','url':'https://api.weather.gc.ca/collections/weather-alerts','attribution':'ECCC / Meteorological Service of Canada. Open Government Licence – Canada. Original alert wording retained.'},{'name':'US National Weather Service','data':'Official US point-filtered alerts','url':'https://www.weather.gov/documentation/services-web-api','attribution':'US National Weather Service / NOAA. US government open data. No no-alert claim on provider failure.'},{'name':'Natural Earth / Astral / timezone data','data':'Offline map, calculated solar events, timezone boundaries','url':'https://www.naturalearthdata.com/','attribution':'Natural Earth public-domain vectors. Astral 3.2 solar/moon calculations. tzfpy IANA timezone lookup; no Windows/IP location.'}]
